(define (pascal_triangule_elem depth i)
  (if (or (< depth 2)
          (< i 2)
          (>= i depth))
      1
      (+ (pascal_triangule_elem (- depth 1) (- i 1))
         (pascal_triangule_elem (- depth 1) i))))
(test (pascal_triangule_elem 1 1) 1)
(test (pascal_triangule_elem 2 2) 1)
(test (pascal_triangule_elem 4 2) 3)
(test (pascal_triangule_elem 5 3) 6)
