(define (square-sum-of-2-largest a b c)
  (define (sum-of-squares x y)
    (+ (square x) (square y)))
  (if (> a b)
      (if (> b c)
          (sum-of-squares a b)
          (sum-of-squares a c))
      (if (> a c)
          (sum-of-squares b a)
          (sum-of-squares b c))))
(test (square-sum-of-2-largest 3 1 2) 13)
(test (square-sum-of-2-largest 3 1 2) 13)
(test (square-sum-of-2-largest 3 1 2) 13)
(test (square-sum-of-2-largest 1 2 3) 13)
(test (square-sum-of-2-largest 2 3 1) 13)
(test (square-sum-of-2-largest 2 1 3) 13)
(test (square-sum-of-2-largest 3 3 3) 18)
