(define (square-sum-of-2-largest a b c)
  (define (sum_of_squares x y)
    (+ (square x) (square y)))
  (if (> a b)
      (if (> b c)
          (sum_of_squares a b)
          (sum_of_squares a c))
      (if (> a c)
          (sum_of_squares b a)
          (sum_of_squares b c))))
(test (square-sum-of-2-largest 3 1 2) 13)
(test (square-sum-of-2-largest 3 1 2) 13)
(test (square-sum-of-2-largest 3 1 2) 13)
(test (square-sum-of-2-largest 1 2 3) 13)
(test (square-sum-of-2-largest 2 3 1) 13)
(test (square-sum-of-2-largest 2 1 3) 13)
(test (square-sum-of-2-largest 3 3 3) 18)
