(define (recursive-k-continued-fraction n d k)
  (define (rec i)
    (if (<= i k)
        (/ (n i) (+ (d i) (rec (++ i))))
        0))
  (rec 1))
(define (k-continued-fraction n d k)
  (define (iter i r)
    (if (> i 0)
        (iter (-- i) (/ (n i) (+ (d i) r)))
        r))
  (iter k 0))
(define (one i) 1.)
(write-line golden-ratio)
(write-line (/ 1 (k-continued-fraction one one 1)))
(write-line (/ 1 (k-continued-fraction one one 10)))
(write-line (/ 1 (k-continued-fraction one one 11)))
(write-line (/ 1 (k-continued-fraction one one 12)))
(write-line (/ 1 (k-continued-fraction one one 15)))
(write-line (/ 1 (k-continued-fraction one one 20)))
(write-line (/ 1 (recursive-k-continued-fraction one one 1)))
(write-line (/ 1 (recursive-k-continued-fraction one one 10)))
(write-line (/ 1 (recursive-k-continued-fraction one one 11)))
(write-line (/ 1 (recursive-k-continued-fraction one one 12)))
(write-line (/ 1 (recursive-k-continued-fraction one one 15)))
(write-line (/ 1 (recursive-k-continued-fraction one one 20)))
