(define (k-continued-fraction n d k)
 (define (iter i r)
  (if (> i 0)
   (iter (-- i) (/ (n i) (+ (d i) r)))
   r))

 (iter k 0))

(define (one i)
 1.0)

(define (recursive-k-continued-fraction n d k)
 (define (rec i)
  (if (<= i k)
   (/ (n i) (+ (d i) (rec (++ i))))
   0))

 (rec 1))

(print-line golden-ratio)
(print-line (/ 1 (k-continued-fraction one one 1)))
(print-line (/ 1 (k-continued-fraction one one 10)))
(print-line (/ 1 (k-continued-fraction one one 11)))
(print-line (/ 1 (k-continued-fraction one one 12)))
(print-line (/ 1 (k-continued-fraction one one 15)))
(print-line (/ 1 (k-continued-fraction one one 20)))
(print-line (/ 1 (recursive-k-continued-fraction one one 1)))
(print-line (/ 1 (recursive-k-continued-fraction one one 10)))
(print-line (/ 1 (recursive-k-continued-fraction one one 11)))
(print-line (/ 1 (recursive-k-continued-fraction one one 12)))
(print-line (/ 1 (recursive-k-continued-fraction one one 15)))
(print-line (/ 1 (recursive-k-continued-fraction one one 20)))
