(define (k-continued-fraction n d k)
 (define (iter i r)
  (if (> i 0)
   (iter (- i 1) (/ (n i) (- (d i) r)))
   r))

 (iter k 0))

(define (tan-cf x k)
 (k-continued-fraction (lambda (i)
                        (expt x i))
                       (lambda (i)
                        (++ (* (-- i) 2)))
                       k))

(write-line (tan 0))
(write-line (tan (/ pi 6)))
(write-line (tan (/ pi 4)))
(write-line (tan (/ pi 2)))
(write-line (tan pi))
(write-line (tan (* pi 2)))
(newline)
(define iterations 100)
(write-line (tan-cf 0 iterations))
(write-line (tan-cf (/ pi 6) iterations))
(write-line (tan-cf (/ pi 4) iterations))
(write-line (tan-cf (/ pi 2) iterations))
(write-line (tan-cf pi iterations))
(write-line (tan-cf (* pi 2) iterations))
